### PR TITLE
Add sample script to geocode Zika data

### PR DESCRIPTION
**Pull request by emily-noble**
This PR adds a script that demonstrates geocoding Zika data to determine what state in Brazil a row is located in based on the latitude and longitude.

The script is intended to be run interactively and prompts the user for:

- Email address
- Data source
  - If Data Dryad, automatically downloads the appropriate documents from Data Dryad and prompts for a specific CSV file
  - If a local data source, prompts for the file path
  - If the included sample data source, automatically opens that file

The script will write to a new file, which has the same name as the input file, but with "_annotated" appended to the end. The output file includes the original columns and the additional columns from geocoding. The additional columns are:

- GEOCODED_STATE_NAME - The name of the state (UTF-8 format)
- GEOCODED_STATE_CODE - The state code (according to [Wikipedia](https://en.wikipedia.org/wiki/States_of_Brazil#List))
- GEOCODED_COUNTRY_NAME - The name of the country (this script will filter everything to just Brazil, so every value should be "Brasil")
- GEOCODED_COUNTRY_CODE - The country code (this script filters only to Brazil, so every value should be "br")

It uses the [Nominatim API](https://nominatim.org/release-docs/develop/api/Reverse/) which requires the user provide an email address and waits at least 1 second between requests. Nominatim uses OpenStreetmap data.

Running against a the full Zika data set will take several hours, mostly due to the rate limit on the Nominatim API.

_Note: I'm new to R so I would appreciate style and convention feedback._

### CODE REVIEW

**Comment by emily-noble** [comment]
@corybrunson I've completed a solid first cut; let me know when you've had a chance to review.

**Comment by corybrunson** [comment]
@emily-noble on it! Thank you. One thing i immediately realized is that it would be better for the example file to consist of the data from one Brazilian state. That's because [the original study](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0192120) computed persistent homology separately for each state, as a measure of the complexity of the state-specific incidence.

@rrrlw i should have opened an issue for this PR first—sorry! We discussed installing some example persistence data with ggtda, but the Zika data used in the study is actually point cloud data, so it made sense to me to consider installing it with ripserr. @emily-noble accomplished some wrangling that i could not and prepared a script to reproduce it. The state-level coordinate data, for all of Brazil, is what i think would be appropriate to install with the package. A vignette could then reproduce some results from the study. As you have the bandwidth, please let me know what you think! In the meantime, i'll address any issues i can find with the PR.

**Comment by rrrlw** [comment]
This looks fantastic, thank you for the contribution! I apologize, looks like the next couple days will keep me busy, but will certainly take a look after.

I agree that this fits well w/ a ripserr vignette. IMO, it would also fit well within a ripserr arXiv preprint. My favorite software papers have all had nice examples within them that have added meaningful value to the manuscript. This example would certainly fit the bill.

I am currently preparing a ripserr preprint in the `preprint` branch of this repo. After I fix the current content and this example has been added as a vignette, would y'all be willing to add the example to the preprint as well? I believe replicating the original paper would be useful to readers - what do y'all think, @emily-noble & @corybrunson?

**Comment by rrrlw** [comment]
P.S. - @corybrunson do you need push access to this repo to work on the PR?

**Comment by emily-noble** [comment]
I'm happy to merge this code wherever you'd like. Actually, if you want I can update this PR to merge into the preprint branch instead of master. 

I'll also take @corybrunson 's suggestion to update the sample data file to be specific to only one state, but will need to do that another day. 

I also want to check on some terminology I'm not super familiar with to make sure I understand fully:

Preprint - you're referring to a publication of the paper before it is formally published in a journal?

Vignette - you're referring to a small script that will compute persistent homology based on the results from geocoding? Presumably that's something one of you would be writing because that's way out of my wheelhouse (I'm a GIS software developer IRL).

**Comment by corybrunson** [comment]
@rrrlw great, and i'll also be only intermittently available for the next couple of weeks. Your suggestion makes sense, though i'll need to give the preprint a read. What journal do you have in mind for it? As for working on the PR, i don't know if i need push access to one repo or even to both. But i'll let y'all know if i have difficulty.

@emily-noble you're correct about both terms! R packages are often "published" not only on CRAN but also in software journals like _The R Journal_ and the _Journal of Open Source Software_, and preprints for both are often put on the arXiv. R packages have specific units of code called vignettes that serve as long-form documentation, often more detailed than the manual and usually structured as case studies using multiple package components to solve an illustrative problem.

Once the geocoding script is finished and the data frame is generated that will be installed with the package (it will go into the `data` folder), i can prepare a vignette that (hopefully!) reproduces the results of the original paper. To recap:

1. Finish script to pre-process Brazilian _aegypti_ data and save as a data frame to install with ripserr.
2. Add manual documentation for the data frame.
3. Write a vignette using the data frame and PH to reproduce the results of the study. (This will require combination with some other data used in the study, in particular the incidence of Zika cases, which are accessible via the Wayback Machine.)
4. Incorporate a summary of the vignette into the preprint.

Does that look right? As for the branches, i don't guess i have a strong opinion. Though i think the completion of `geocode-data` is a prerequisite for the use of the data set in the preprint, so i'd suggest keeping them separate for now.

**Comment by emily-noble** [comment]
My latest push changes the sample data set to be from only one state. In this case it's Acre and also happens to include all the data from that state (from the aegypti.csv file from Data Dryad).

**Comment by corybrunson** [comment]
@emily-noble do you have any idea why my local Git would not be able to find your remote? It found my fork just fine. (I began by cloning the original, then added my fork as a downstream remote.)

**Comment by corybrunson** [comment]
@emily-noble Argh, never mind. I left off the name of the repo (overcorrecting for removing the branch name) and took a while to notice it.

**Comment by corybrunson** [comment]
@rrrlw this branch satisfies a basic check on my machine, but i can't seem to run a check on Travis-CI. If that's a concern, perhaps you could merge this PR into a new branch? Otherwise, i'm on board with merging it into `main`. : )

**Comment by rrrlw** [comment]
Apologies for taking so long to get back to y'all. This looks great! Seriously commend y'all on the detail of the documentation + replication script, I hope to emulate this in any contributions I make.

I am willing to merge this directly into `main`. Let's work on the `vignette` in a branch or fork?

Before I merge into `main`, would each of you be willing to add yourselves to DESCRIPTION under Authors@R with role = "aut"? This was a solid contribution w/ code + data that will eventually be added as a vignette and within a preprint as well.

**Comment by emily-noble** [comment]
@rrrlw both of us should be added to the authors now.

**Comment by rrrlw** [comment]
Thank you @emily-noble and @corybrunson! Merging now.

@emily-noble: I believe that you contributed a substantial amount to `ripserr` and have certainly earned the "aut" role, but I respect your decision to be added as "ctb" instead of "aut". I have two questions for you:
1. Would you feel comfortable contributing to the vignette and/or preprint mentioned above? If so, would you feel comfortable being added as a co-author on either or both of them?
2. If yes to the previous question, would you be comfortable with me switching your "ctb" to "aut" prior to CRAN submission? (unsure of the exact timeline)

**Pull request merged**
