### PR TITLE
Create vignette to demo usage of PH

### PR DESCRIPTION
**Pull request by XinyiEmilyZhang**
Hello Raoul, I added a vignette on using PH to model the mosquito-borne disease. This vignette serves as a guide for demonstrating the use of PH from "ripserr". Please take a look at it and see if it fits well with the package. Thanks!

### CODE REVIEW

**Comment by corybrunson** [comment]
@rrrlw something to mention here is that we've both hit errors while building the vignette using `R CMD check`. I haven't been able to trace the problem, so i wanted to ask if you also encounter it.

Of course, additional feedback on the vignette itself would be welcome. : )

**Comment by rrrlw** [comment]
@XinyiEmilyZhang & @corybrunson: thank you for this contribution! I will look over it, hopefully over the next week. I'll make sure to look at the `R CMD check` output as well.

In the meantime, @XinyiEmilyZhang, would you please add another commit to your fork adding yourself as an author (`role = "aut"`) in the `DESCRIPTION` file? This is a substantive contribution, IMO.

**Review by rrrlw — CHANGES_REQUESTED** [review]
I apologize for the delay.

I have added a few edits in commits d1332c4 and a5de583, please look them over; they are subjective, so feel free to reject/further edit anything I changed.

A couple of points regarding R CMD check:
* 1 WARNING because the zikaPredict dataset (included in the data directory) is not documented. **Would either of you be willing to document this dataset analogous to how `aegypti` is documented in `R/data.r`?**
* 1 NOTE because the installed package size is larger than 5 MB; I don't think this will pose an issue for CRAN (was present in the current CRAN version of ripserr as well - due to Rcpp, I believe)
* 1 NOTE stating "found 2196 marked UTF-8 strings"; I do not know why this is a problem because DESCRIPTION includes the `Encoding: UTF-8` line. However, if this is going to pose an issue for CRAN, we might as well convert the UTF-8 markings to ASCII. After loading the `aegypti` dataset, running `stringi::stri_enc_isascii(aegypti$state_name) %>% magrittr::not %>% sum` to check whether content is ASCII returns 2196 (essentially saying 2196 elements in `aegypti$state_name` contained non-ASCII characters). This may correspond to the cedillas and accents used in the Portuguese state names. **Would y'all be willing to convert them to ASCII?** For instance, by replacing `Paraná` with `Parana` (no accent). I dislike changing the name from its native spelling, but I think we can correct it in the plot titles separately if we'd like.

I don't see any other issues on R CMD check, do y'all?

**Comment by corybrunson** [comment]
@rrrlw thank you for the detailed requests! Your own commits look fine—largely separating sentences into lines, which certainly makes `diff`ing easier.

@XinyiEmilyZhang i would be glad to add documentation for `zikaPredict` and to replace the non-ASCII characters in the state names. Please let me know if that's OK with you. I would ask you to review my documentation when it's finished before completing the PR.

**Comment by XinyiEmilyZhang** [comment]
> I apologize for the delay.
> 
> I have added a few edits in commits [d1332c4](https://github.com/rrrlw/ripserr/commit/d1332c471188b1585b9bb27db5324aa1f8b7dbc2) and [a5de583](https://github.com/rrrlw/ripserr/commit/a5de583533412f9dd25bb094a52c36ceaa0acb09), please look them over; they are subjective, so feel free to reject/further edit anything I changed.
> 
> A couple of points regarding R CMD check:
> 
> * 1 WARNING because the zikaPredict dataset (included in the data directory) is not documented. **Would either of you be willing to document this dataset analogous to how `aegypti` is documented in `R/data.r`?**
> * 1 NOTE because the installed package size is larger than 5 MB; I don't think this will pose an issue for CRAN (was present in the current CRAN version of ripserr as well - due to Rcpp, I believe)
> * 1 NOTE stating "found 2196 marked UTF-8 strings"; I do not know why this is a problem because DESCRIPTION includes the `Encoding: UTF-8` line. However, if this is going to pose an issue for CRAN, we might as well convert the UTF-8 markings to ASCII. After loading the `aegypti` dataset, running `stringi::stri_enc_isascii(aegypti$state_name) %>% magrittr::not %>% sum` to check whether content is ASCII returns 2196 (essentially saying 2196 elements in `aegypti$state_name` contained non-ASCII characters). This may correspond to the cedillas and accents used in the Portuguese state names. **Would y'all be willing to convert them to ASCII?** For instance, by replacing `Paraná` with `Parana` (no accent). I dislike changing the name from its native spelling, but I think we can correct it in the plot titles separately if we'd like.
> 
> I don't see any other issues on R CMD check, do y'all?

@rrrlw Thank you so much for checking the vignette and those changes look very positive! As being said, it is totally fine to let @corybrunson change state names and make documentation for the dataset. Thanks!

**Comment by XinyiEmilyZhang** [comment]
@rrrlw I think we have made all changes you requested. I ran the devtools::check() now it gives me no errors. Please see if this also executes well on your machine. Of course, any additional feedback is welcome! Thanks.

**Pull request merged**
